-- Real client testimonials (approved, source admin). Already applied to production (dhuahskektxsztgyetnl) and dev (zwtzncewhigoqzforzjh); do not re-run.
-- Photos live in the destinations bucket on that project; re-upload them if seeding a different project.
-- Destinations and trip years are placeholders to be corrected from the admin dashboard.

insert into testimonials (name, destination, trip_year, quote, photo_url, status, source, display_order) values
('Care', 'Seychelles', 2026, 'When you contact Ijoba Travels and they ask, "What do you want, and how do you want it?" they genuinely mean it. They take the time to understand exactly what you''re looking for and then deliver an experience that exceeds your expectations.

That was exactly how my Seychelles trip turned out. It was everything I imagined and more. I wanted a peaceful escape where I could relax, recharge, and still enjoy memorable experiences, all while staying within my budget, and they delivered exactly that.

From the breathtaking beaches and stunning scenery to the seamless travel arrangements and thoughtful recommendations, every part of the journey was carefully planned. I never had to worry about the logistics, which allowed me to simply soak in the beauty of Seychelles and enjoy every moment. It was the perfect balance of relaxation and exploration.

What impressed me most was how well they listened to what I wanted. This wasn''t just another travel package; it was tailored specifically to my preferences. Finding a travel agency that combines personalization, quality, and affordability is rare, but Ijoba Travels did just that.

Thank you for making the trip a reality and for aiding to  create memories that will stay with me forever. I highly recommend Ijoba Travels to anyone looking for a well planned, stress free travel experience. Ijoba!!! Unto the next trip…', 'https://dhuahskektxsztgyetnl.supabase.co/storage/v1/object/public/destinations/testimonials/care_1791298013717.png', 'approved', 'admin', 0),
('Philemon', 'Nigeria', 2026, 'Ijoba Travels designed the ultimate vacation for us. We were completely swept away, moving seamlessly from the vibrant, electric rhythm of Lagos to the serene, magical wonder of Ikogosi Warm Springs. The refreshing scenery of where the cold and warm springs meet but do not mix was really mind blowing.
The logistics was flawless, leaving us entirely free to immerse ourselves in the romance and beauty of the experience.
If you want a spectacular, stress-free getaway that you''ll remember forever, look no further!', 'https://dhuahskektxsztgyetnl.supabase.co/storage/v1/object/public/destinations/testimonials/philemon_1791298016177.png', 'approved', 'admin', 1),
('Israel', 'Kenya', 2026, 'From our very first conversation, I knew I wasn''t just getting another generic vacation package. Ijoba Travels actually listened. They took my personal preferences and turned them into a bespoke itinerary crafted entirely for me. It is incredibly rare to find an agency that delivers this level of deep personalization and premium quality without breaking the bank, but they pulled it off effortlessly.
You didn''t just plan a trip; you helped me unlock unforgettable moments that I will look back on for the rest of my life. For an adventure that is meticulously detailed and completely stress-free, I cannot recommend them enough.', 'https://dhuahskektxsztgyetnl.supabase.co/storage/v1/object/public/destinations/testimonials/israel_1791298018638.jpg', 'approved', 'admin', 2),
('Juliet', 'Seychelles & Kenya', 2026, 'My experience with Ijoba Travels was nothing short of amazing. The trip was very affordable, yet the quality exceeded my expectations. We visited both Seychelles and Kenya and stayed in beautiful city-view and sea-view apartments that offered great comfort and value for money. One of the highlights of the trip was the wide variety of activities available—there were so many that we couldn''t even keep up with all of them! What made the experience even more enjoyable was the flexibility to choose and add activities on the go, allowing us to personalize our itinerary and make every day more exciting. The planning, organization, and support from the Ijoba Travels team were excellent from start to finish. I highly recommend Ijoba Travels to anyone looking for an affordable, well-organized, and unforgettable travel experience.', 'https://dhuahskektxsztgyetnl.supabase.co/storage/v1/object/public/destinations/testimonials/juliet_1791298020022.jpg', 'approved', 'admin', 3);
